### ISSUE TITLE
Supprimer les tests

### ISSUE THREAD

**Issue by P0ppoff** [Zenika/grenoble-hands-on-angular#5]
C’est pas sur *craft* de faire ça mais pour le projet je ne pense que pas que ça vaut le coup de mettre des tests. On risque de perdre des gens.

**Comment by mchoraine** [comment]
Je sais pas... Je veux bien qu'on en rediscute. Parce qu'il y a eu quelques demandes pour les tests.
Ensuite ces fichiers sont crées par le cli. C'est peut etre dommage d'explicitement les enlever.

**Comment by P0ppoff** [comment]
8eb05a5ccae52f6580f775f8f45d06bd72615e33
